version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s [%(levelname)s] %(name)s:%(lineno)s: %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    file:
         class: logging.handlers.RotatingFileHandler
         level: DEBUG
         formatter: simple
         filename: logs/sm.log
         maxBytes: 10485760
         backupCount: 20
         encoding: utf8

loggers:
    "":
        level: DEBUG
        handlers: [console, file]

root:
    level: DEBUG
    handlers: [console, file]
